version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-andrew}"
    image: cybulde-data-preparation
    container_name: cybulde-data-preparation-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/ml-apps-409905-be3082008c87.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-andrew}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
    ports:
      - 8888:8888

    ipc: host
    init: true


